config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :customers
  resources :products
  resources :receipts do
    resources :purchases
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :purchases
#   has_many :products, :through => :purchases
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :purchases
#   has_many :customers, :through => :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
  belongs_to :customer
  belongs_to :receipt
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_many :purchases
#   has_many :customers, :through => :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
    render :index
  end

  def new
    @customer = Customer.new
    render :new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path
    else
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
    render :edit
  end

  def show
    @customer = Customer.find(params[:id])
    render :show
  end

  def update
    @customer= Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end

  private
    def customer_params
      params.require(:customer).permit(:name)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :stock)
    end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @receipt = Receipt.find(params[:receipt_id])
    @purchases = @receipt.purchases.all
    # render :index
    redirect_to receipts_path

  end

  def new
    @receipt = Receipt.find(params[:receipt_id])
    @purchase = @receipt.purchases.new
    @customers = Customer.all
    render :new
  end

  def create
    @receipt = Receipt.find(params[:receipt_id])
    @purchase = @receipt.purchases.new(purchase_params)

    if @purchase.save
      # render :new
      redirect_to new_receipt_purchase_path(@receipt)
    else
      render :new
    end

  end

  def edit
    @receipt = Receipt.find(params[:receipt_id])
    @purchase = Purchase.find(params[:id])
    render :edit
  end

  def show
    @receipt = Receipt.find(params[:receipt_id])
    @purchase = Purchase.find(params[:id])
    @customer = Customer.find(@purchase.customer_id)
    @product = Product.find(@purchase.product_id)

    render :show
  end

  def update
    @purchase= Purchase.find(params[:id])
    if @purchase.update(purchase_params)
      redirect_to receipt_path(@purchase.receipt)
    else
      render :edit
    end
  end

  def destroy
    @receipt = Receipt.find(params[:receipt_id])
    @purchase = @receipt.purchases.destroy

    # @purchase = Purchase.find(params[:id])
    # @purchase.destroy
    redirect_to receipt_purchases_path
  end

  private
    def purchase_params
      params.require(:purchase).permit(:product_id, :customer_id, :receipt_id, :date)
    end

end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

  def index
    @receipts = Receipt.all
    render :index
  end

  def new
    @receipt = Receipt.new
    render :new
  end

  def create
    @receipt = Receipt.new
    if @receipt.save
      render :show
    else
      render :new
    end
  end

  def edit
    @receipt = Receipt.find(params[:id])
    render :edit
  end

  def show
    @receipt = Receipt.find(params[:id])
    @purchases = @receipt.purchases.all


    render :show
  end

  def update
    @receipt = Receipt.find(params[:id])
    if @receipt.update(receipt_params)
      redirect_to receipts_path
    else
      render :edit
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy
    redirect_to receipts_path
  end

  # private
  # def receipt_params
  #   params.require().permit()
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/edit.html.erb
<h1>Edit customer</h1>

<%= form_for @customer do |f| %>
<%= f.label :name  %>
<%= f.text_field :name %>
<p><%= f.submit %></p>
<% end %>

app/views/customers/index.html.erb
<h1>Customers</h1>

<% if @customers.any? %>
<ul>
  <% @customers.each do |customer| %>
  <li><%= link_to customer.name, customer_path(customer) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no customers yet!</p>
<% end %>

<p><%= link_to "Add a new customer", new_customer_path %></p>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= form_for @customer do |f| %>
<%= f.label :name  %>
<%= f.text_field :name %>
<p><%= f.submit %></p>
<% end %>

app/views/customers/show.html.erb
<h1><%= @customer.name %></h1>

<p><%= link_to "Edit", edit_customer_path(@customer) %> </p>
<p><%= link_to "Delete", customer_path(@customer), :data => {:confirm => "Really??", :method => "delete"} %></p>

<p><%= link_to "Return to customers", customers_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
<div class="jumbotron">
<h1>ANTIQUES!!!!</h1>

<p><%= link_to "Customers", customers_path %> |
<%= link_to "Products", products_path %> |
<%= link_to "Receipts", receipts_path %></p>


</div>
      <%= yield %>

      <a href="/">HOME!!</a>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<% if @products.any? %>
<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet!</p>
<% end %>

<p><%= link_to "Add a new product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New customer</h1>

<%= form_for @product do |f| %>
<%= f.label :name  %>
<%= f.text_field :name %>
<%= f.label :price %>
<%= f.number_field :price, min: 0, step: 0.01  %>
<%= f.label :stock %>
<%= f.number_field :stock %>
<p><%= f.submit %></p>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h2>$<%= @product.price %></h2>
<h2><%= @product.stock %></h2>

<p><%= link_to "Edit", edit_product_path(@product) %> </p>
<p><%= link_to "Delete", product_path(@product), :data => {:confirm => "Really??", :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/purchases/edit.html.erb
<h1>Edit purchase</h1>

<%= form_for [@receipt, @purchase] do |f| %>

<%= f.label :product_id  %>
<%= collection_select(:purchase, :product_id, Product.all, :id, :name) %>
product_id_array.push(:id)




<%= f.label :customer_id  %>
<%= collection_select(:purchase, :customer_id, Customer.all, :id, :name) %>

<%= f.label :date %>
<%= datetime_select Date.today, prefix: :date %>

<%= f.label :receipt_id %>
<%= f.number_field :receipt_id %>


<p><%= f.submit %></p>
<% end %>

app/views/purchases/index.html.erb
<h1>Purchases</h1>

<% if @purchases.any? %>
<ul>
  <% @purchases.each do |purchase| %>
  <li><%= link_to purchase.product.name, receipt_purchase_path(@receipt) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no purchases yet!</p>
<% end %>

<p><%= link_to "Add a new purchase", new_purchase_path %></p>

app/views/purchases/new.html.erb
<h1>New purchases</h1>

<%= form_for [@receipt, @purchase] do |f| %>

<%= f.label :product_id  %>
<%= collection_select(:purchase, :product_id, Product.all, :id, :name) %>




<%= f.label :customer_id  %>
<%= collection_select(:purchase, :customer_id, Customer.all, :id, :name) %>

<%= f.label :date %>
<%= datetime_select Date.today, prefix: :date %>

<%= f.label :receipt_id %>
<%= f.number_field :receipt_id %>


<p><%= f.submit %></p>
<% end %>

app/views/purchases/show.html.erb
<h1>Purchase #: <%= @purchase.id %></h1>
<h2>Customer: <%= @customer.name %></h2>
<h2>Product: <%= @product.name %></h2>
<h1>Transaction: <%= @purchase.receipt_id %></h1>


<p><%= link_to "Edit", edit_receipt_purchase_path(@receipt) %> </p>
<p><%= link_to "Delete", receipt_purchase_path(@receipt), :data => {:confirm => "Really??", :method => "delete"} %></p>

<p><%= link_to "Return to purchases", receipt_purchases_path %></p>

app/views/receipts/edit.html.erb
<h1>Edit receipt</h1>

<%= form_for @receipt do |f| %>
<p><%= f.submit %></p>
<% end %>

app/views/receipts/index.html.erb
<h1>Receipts</h1>

<% if @receipts.any? %>
<ul>
  <% @receipts.each do |receipt| %>
  <li><%= link_to receipt.id, receipt_path(receipt) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no receipts yet!</p>
<% end %>

<p><%= link_to "Add a new receipt", new_receipt_path %></p>

app/views/receipts/new.html.erb
<h1>New receipt</h1>

<%= form_for @receipt do |f| %>
<p><%= f.submit %></p>
<% end %>

app/views/receipts/show.html.erb
<h1><%= @receipt.id %></h1>


<p><%= link_to "create new purchase", new_receipt_purchase_path(@receipt) %> </p>
<p><%= link_to "Delete", receipt_path(@receipt), :data => {:confirm => "Really??", :method => "delete"} %></p>

<p><%= link_to "Return to receipts", receipts_path %></p>


<HR>
  <h1>Purchases</h1>

  <% if @purchases.any? %>
  <ul>
    <% @purchases.each do |purchase| %>
    <li><%= link_to purchase.product.name, receipt_purchase_path(@receipt) %></li>
    <% end %>
  </ul>
  <% else %>
  <p>There are no purchases yet!</p>
  <% end %>

  <p><%= link_to "Add a new purchase", new_receipt_purchase_path(@receipt) %></p>

  <HR>